projects:
  - name: "Atelier Go"
    path: "~/Projects/AtelierGo/atelier-go/"
  - name: "Workstation Home"
    path: "~/"
    shell-default: true
  - name: "TourneyMate Backend"
    path: "~/Projects/TourneyMate/tourneymate-backend/"
