projects:
  - name: "Atelier Go"
    path: "~/Projects/AtelierGo/atelier-go/"
  - name: "Workstation Home"
    path: "~/"
    shell-default: true
  - name: "TourneyMate Backend"
    path: "~/Projects/TourneyMate/tourneymate-backend/"
    actions:
      - name: "Dev Server"
        command: "go run main.go serve --http=\"0.0.0.0:8090\""
