# Work Laptop Config
actions:
  - name: "Gemini"
    command: "gemini"
projects:
  - name: "Gemini Notes"
    path: "~/Projects/Gemini-Notes/gemini-notes/"
  - name: "LazyNotes"
    path: "~/Projects/LazyNotes/lazynotes/"
