actions:
  - name: "OpenCode"
    command: "opencode"
  - name: "Gemini"
    command: "gemini"
projects:
  - name: "TourneyMate App"
    path: "~/Projects/tourneymate-app/"
  - name: "Atelier Go"
    path: "~/Projects/atelier-go/"
